### ISSUE TITLE
Calculate cyclic complexity for function #4, centerPointForNormal

### ISSUE THREAD

**Issue by EdvinArdo** [DD2480-Group17/assignment3#10]

**Comment by Marcus9512** [comment]
Class: AABB
Method: centerPointForNormal(Vector3f)

**Comment by johannaii** [comment]
Is the function just complex, or also long?
What is the purpose of the function?

**Comment by Marcus9512** [comment]
1. What are your results? Did everyone get the same result? Is there something that is unclear? If you have a tool, is its result the same as yours?

Yes everyone got the same result on the complexity.
The result is: M = B - D + 1= 36 - 18 +1 = 19
Jacoco: 19

Forumla presented during leacture (gave not the same answer): M = 18 - 7 +2 = 13

2. Are the functions/methods with high CC also very long in terms of LOC?

No it´s not, the lenght is only 20 lines of code.

3. What is the purpose of these functions? Is it related to the high CC?

The purpose of this function is to compute the centerpoint of six available planes given a normal. I´s understandable that this function has high complexity becuse ther are sevral criterias that needs to be checked. This will result in alot of nested if statments that will increase the complexity.

4. If your programming language uses exceptions: Are they taken into account by the tool? If you think of an exception as another possible branch (to the catch block or the end of the function), how is the CC affected?

No exceptions are handled by this function.

5. Is the documentation of the function clear about the different possible outcomes induced by different branches taken?

No, it´s not clear at all what the function does, the only thing that is documented is what the function does, but not clearly explained.
