### ISSUE TITLE
Calculate cyclic complexity for function #1: mergeFrom(NetData.NetMessage)

### ISSUE THREAD

**Issue by EdvinArdo** [DD2480-Group17/assignment3#7]

**Comment by EdvinArdo** [comment]
Cyclomatic complexity according to tools: 79
π − s + 2 = 78 -2 + 2 = 78

**Comment by johannaii** [comment]
Is the function just complex, or also long?
What is the purpose of the function?

**Comment by EdvinArdo** [comment]
The function is very long, ~300 LOC.

The purpose of the function is to create a merge two Builders into one, which can build NetMessages.
